CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       full_name VARCHAR(255) NOT NULL,
                       password VARCHAR(255)
);

CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          account_number VARCHAR(255) NOT NULL UNIQUE,
                          balance NUMERIC(19,2) NOT NULL,
                          user_id BIGINT NOT NULL,

                          CONSTRAINT fk_accounts_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users(id)
);

CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              amount NUMERIC(19,2) NOT NULL,
                              created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              type VARCHAR(255) NOT NULL,
                              account_id BIGINT NOT NULL,
                              target_account_id BIGINT,

                              CONSTRAINT chk_transactions_type
                                  CHECK (type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER')),

                              CONSTRAINT fk_transactions_account
                                  FOREIGN KEY (account_id)
                                      REFERENCES accounts(id),

                              CONSTRAINT fk_transactions_target_account
                                  FOREIGN KEY (target_account_id)
                                      REFERENCES accounts(id)
);