CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR(255) NOT NULL UNIQUE,
                                expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                                user_id BIGINT NOT NULL,

                                CONSTRAINT fk_refresh_tokens_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users(id)
                                        ON DELETE CASCADE
);